 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/horarios", type: :request do
  # Horario. As you add validations to Horario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Horario.create! valid_attributes
      get horarios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      horario = Horario.create! valid_attributes
      get horario_url(horario)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_horario_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      horario = Horario.create! valid_attributes
      get edit_horario_url(horario)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Horario" do
        expect {
          post horarios_url, params: { horario: valid_attributes }
        }.to change(Horario, :count).by(1)
      end

      it "redirects to the created horario" do
        post horarios_url, params: { horario: valid_attributes }
        expect(response).to redirect_to(horario_url(Horario.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Horario" do
        expect {
          post horarios_url, params: { horario: invalid_attributes }
        }.to change(Horario, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post horarios_url, params: { horario: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested horario" do
        horario = Horario.create! valid_attributes
        patch horario_url(horario), params: { horario: new_attributes }
        horario.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the horario" do
        horario = Horario.create! valid_attributes
        patch horario_url(horario), params: { horario: new_attributes }
        horario.reload
        expect(response).to redirect_to(horario_url(horario))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        horario = Horario.create! valid_attributes
        patch horario_url(horario), params: { horario: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested horario" do
      horario = Horario.create! valid_attributes
      expect {
        delete horario_url(horario)
      }.to change(Horario, :count).by(-1)
    end

    it "redirects to the horarios list" do
      horario = Horario.create! valid_attributes
      delete horario_url(horario)
      expect(response).to redirect_to(horarios_url)
    end
  end
end
